title: Plank Reloaded
description: Plank Reloaded is a fork of the original Plank project, providing a simple dock for X11 desktop environments. While development began with a focus on Cinnamon, we now actively support multiple desktop environments including MATE and Xfce. Wayland is not supported at this time.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
