---
name: Build and Release - Ubuntu Noble Numbat

on:
  release:
    types: [created]

jobs:
  build:
    name: Build on Ubuntu Noble Numbat
    runs-on: ubuntu-latest
    container: ubuntu:noble

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git \
            dpkg \
            dpkg-dev \
            lintian \
            cmake \
            gettext \
            desktop-file-utils \
            libdbusmenu-glib-dev \
            libdbusmenu-gtk3-dev \
            meson \
            ninja-build \
            valac \
            libgnome-menu-3-dev \
            libxml2-utils \
            libgtk-3-dev \
            libgee-0.8-dev \
            libbamf3-dev \
            libwnck-3-dev \
            bamfdaemon

      - name: Build
        run: |
          meson setup --prefix=/usr build
          meson configure build -D enable-apport=false -D production-release=true
          meson compile -C build
          meson install --destdir="$(pwd)/release_build" -C build

      - name: Package
        run: |
          mkdir -p dist/plank-reloaded
          cp -r release_build/* dist/plank-reloaded/
          cp -r DEBIAN dist/plank-reloaded/
          cd dist
          mv plank-reloaded/DEBIAN/changelog plank-reloaded/usr/share/doc/plank-reloaded/changelog.Debian
          mv plank-reloaded/DEBIAN/copyright plank-reloaded/usr/share/doc/plank-reloaded/
          gzip -9n plank-reloaded/usr/share/doc/plank-reloaded/changelog.Debian
          gzip -9n plank-reloaded/usr/share/man/man1/plank.1
          strip --strip-unneeded plank-reloaded/usr/bin/plank
          strip --strip-unneeded plank-reloaded/usr/lib/x86_64-linux-gnu/libplank.so.1.0.0
          find plank-reloaded/usr/lib/x86_64-linux-gnu/plank/docklets/ -type f -name "*.so" -exec strip --strip-unneeded {} \;
          dpkg-deb --build plank-reloaded

      - name: Run Lintian
        run: |
          cd dist
          lintian plank-reloaded.deb || true

      - name: Verify Package
        run: |
          cd dist
          dpkg --info plank-reloaded.deb
          dpkg --contents plank-reloaded.deb

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/plank-reloaded.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
